### ISSUE TITLE
Consider using LIBPHONENUMBER

### ISSUE THREAD

**Issue by g1smd** [splitbrain/googlephonefix#1]
Google library LIBPHONENUMBER already has rules for parsing phone numbers for 228 countries/regions, and formatting/validating phone numbers for 200 countries/regions of the world.

http://code.google.com/p/libphonenumber/

**Comment by splitbrain** [comment]
Wow, cool. I searched for something like but couldn't find anything. This looks useful - I'll have a look at it.

**Comment by splitbrain** [comment]
I implemented the use of libphonenumber in a second branch. But I'm not too happy with the results it produces.

**Comment by g1smd** [comment]
What are the problems?

You can post an issue in the tracker, or discuss here.

**Comment by g1smd** [comment]
What are those issues?  What is wrong with the results?

**Comment by splitbrain** [comment]
It wasn't really wrong, it just didn't look like I like phone numbers to look ;-) Eg. I don't like slashes in my numbers. It would probably be possible to add a few additional replacements after your library ran... but since my contacts are already fixed I can't really test this anymore.

**Comment by g1smd** [comment]
From what I can remember, and that's not a lot, someone else asked for the slashes to be included in the German format a long time ago.

Please create an issue in the LIBPHONENUMBER tracker detailing what format you prefer, and why. I do think this is something that should be flagged for the project owners attention and discussed further with them.
